export const SEND_MAIL_QUEUE_NAME = 'send-mail-queue'
export const SEND_ONBOARDING_LINK_JOB_NAME = 'sendOnboardingLinkMail'

// microservices

export const STRIPE_MICROSERVICE_NAME = 'STRIPE_SERVICE'
export const STRIPE_MICROSERVICE_CREATE_CUSTOMER_MESSAGE = 'CREATE_CUSTOMER'
export const STRIPE_MICROSERVICE_GET_CUSTOMER_CARD_MESSAGE = 'GET_CUSTOMER_CARD'